version: "3.9"

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multilingual_rag_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - chroma
    command: >
      uvicorn app.app:app --host 0.0.0.0 --port 8000

  chroma:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
